### ISSUE TITLE
Possibly invalid decompression for lossless JPEG

### ISSUE THREAD

**Issue by malaterre** [thorfdbg/libjpeg#5] opened 2016-08-17 12:22 UTC
Dear Thomas,

I am observing a slightly different behavior in between a well known JPEG-lossless implementation and yours. If you decompress the attached lossless JPEG you'll see a tiny white area (around row 504, col 300). Would you please double check that the decompression as done with libjpeg 1.50 is correct for this input. Thanks.

![UnsupportedMarkerType2b](https://cloud.githubusercontent.com/assets/228803/17736000/b0f0c346-6485-11e6-9560-11847e8155b6.jpg)

**Comment by malaterre** [comment] 2016-08-17 12:34
I can attached the decompressed (gray16be) PGM if needed. Also for complete reference, here is the original thread: https://groups.google.com/d/msg/comp.protocols.dicom/JUuz0B_aE5o/exxhbk-aAAAJ

**Comment by oculushut** [comment] 2017-08-16 13:31
@malaterre just wondering, but could you share the name of the "well known JPEG-lossless implementation" you are comparing this to?  Thanks!

**Comment by thorfdbg** [comment] 2017-08-17 13:26
Am 16.08.2017 um 15:31 schrieb oculushut:
> @malaterre <https://github.com/malaterre> just wondering, but could you 
> share the name of the "well known JPEG-lossless implementation" you are 
> comparing this to? Thanks!

There is unfortunately really an issue with this image which I need to 
fix (or already have fixed in an internal version). However, I cannot 
answer which implementation the OP compared to.

Greetings,
	Thomas

**Comment by thorfdbg** [comment] 2017-08-18 11:27
Hi again,

more complicated than I thought. Even though it looks strange, there is 
no issue with this image. The problem is the following: According to the 
data in the image, the sample left to the "error" sample that starts the 
white line has a value of 3. The predictor tells me that prediction from 
left is enabled, with a prediction delta of -7, giving a value of -4. 
Now, the standard tells me that I should use add the prediction to the 
predicted value, i.e. -7+3 giving -4. The result, however, shall be 
taken modulo 2^16, giving a white pixel.

Note that there is *no clamping* in the lossles mode of JPEG. It is 
using modulo arithmetic.

Greetings,
	Thomas

**Closed** 2017-08-18 19:27 UTC
